#!/bin/sh
touch tmp/restart.txt
echo "restarting Passenger app"
RAILS_ENV=production rake assets:precompile
RAILS_ENV=production rake db:migrate
kill $(cat tmp/pids/server.pid)
rm tmp/pids/server.pid
rails s -e production -p 8080 -d
service apache2 restart